version: '3.8'

services:
  forum:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./internal/database:/app/internal/database
      - ./ui:/app/ui
    environment:
      - PORT=8080
    restart: always
